docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Introduction: intro.md
site_name: zend-i18n-idn 
site_description: 'Polyfill for IDN functions of the PHP Internationalization (intl) extension.'
repo_url: 'https://github.com/zendframework/zend-i18n-idn'
copyright: 'Copyright (c) 2017 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
